export enum CoreContractAccounts {
    AccountsContract = 'accounts',
    Deposit = 'deposit',
    TransferAccountToChain = 'transferAccountToChain',
    TransferAllowanceTo = 'transferAllowanceTo',
    Withdraw = 'withdraw',
    SetCoinMetadata = 'setCoinMetadata',
    DeleteCoinMetadata = 'deleteCoinMetadata',
    ViewAccountObjects = 'accountObjects',
    ViewAccountObjectsInCollection = 'accountObjectsInCollection',
    ViewBalance = 'balance',
    ViewBalanceBaseToken = 'balanceBaseToken',
    ViewBalanceBaseTokenEVM = 'balanceBaseTokenEVM',
    ViewBalanceCoin = 'balanceCoin',
    ViewGetAccountNonce = 'getAccountNonce',
    ViewObjectBCS = 'objectBCS',
    ViewTotalAssets = 'totalAssets',
}
