name: Staging Deploy for the IOTA EVM Bridge

on:
    push:
        branches:
            - main
        paths:
            - '.github/workflows/**'
            - 'app/**'
            - 'sdk/**'

jobs:
    deploy-testnet-staging:
        uses: ./.github/workflows/app-vercel-deploy.yml
        with:
            VERCEL_TARGET: testnet-staging
        secrets:
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
            VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
            EVM_BRIDGE_CONFIG: ${{ secrets.EVM_BRIDGE_CONFIG }}
            EVM_BRIDGE_DEFAULT_NETWORK: ${{ secrets.EVM_BRIDGE_PREVIEW_DEFAULT_NETWORK }}