name: Production Deploy for the EVM Toolkit Rebased

on:
    push:
        branches:
            - main
        paths:
            - 'isc-faucet-depositer/**'
            - 'isc-client/**'

jobs:
    deploy-production:
        uses: ./.github/workflows/app-vercel-deploy.yml
        with:
            PRODUCTION: true
        secrets:
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
            VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
