name: Preview Deploy for the EVM Toolkit Rebased

on:
    workflow_dispatch:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
        paths:
            - '.github/workflows/**'
            - 'app/**'
            - 'sdk/**'

jobs:
    deploy-preview:
        uses: ./.github/workflows/app-vercel-deploy.yml
        with:
            PRODUCTION: false
        secrets:
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
            VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
            EVM_BRIDGE_CONFIG: ${{ secrets.EVM_BRIDGE_CONFIG }}
            EVM_BRIDGE_DEFAULT_NETWORK: ${{ secrets.EVM_BRIDGE_PREVIEW_DEFAULT_NETWORK }}
