name: Production Deploy for the IOTA EVM Bridge

on:
    workflow_dispatch:

jobs:
    deploy-production:
        uses: ./.github/workflows/app-vercel-deploy.yml
        with:
            VERCEL_TARGET: production
        secrets:
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
            VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
            EVM_BRIDGE_CONFIG: ${{ secrets.EVM_BRIDGE_CONFIG }}
            EVM_BRIDGE_DEFAULT_NETWORK: ${{ secrets.EVM_BRIDGE_PROD_DEFAULT_NETWORK }}
