name: Production Deploy for the EVM Toolkit Rebased

on:
    push:
        branches:
            - main
        paths:
            - '.github/workflows/**'
            - 'isc-faucet-depositer/**'
            - 'isc-client/**'

jobs:
    deploy-production:
        uses: ./.github/workflows/app-vercel-deploy.yml
        with:
            PRODUCTION: true
        secrets:
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
            VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
            VITE_NETWORK_NAME: ${{ secrets.NETWORK_NAME }}
            VITE_NETWORK_RPC_L2: ${{ secrets.NETWORK_RPC_L2 }}
            VITE_WALLET_CONNECT_L2_PROJECT_ID: ${{ secrets.WALLET_CONNECT_L2_PROJECT_ID }}

